services:
  streaming-checker:
    image: ghcr.io/gipasoft/streaming-checker:latest
    container_name: streaming-checker
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - qnap-network      
    restart: unless-stopped
    labels:
      - diun.enable=true
networks:
  qnap-network:
    external: true
